import Footer from "./Footer";
import Navbar from "./Navbar";
import Head from "next/head";
import React from "react";
import ScrollToTop from "./ScrollToTop";



const myLoader = ({ src, width, quality }) => {
    return `https://drcutthebarbershow.web.app/${src}?w=${width}&q=${
      quality || 75
    }`;
  };
  

function Layout({children}) {
    return (
        <React.StrictMode>
        <Head>
        <title>Dr.Cut The Barber Show</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container-fluid p-0 " data-spy="scroll" data-target="#mainNav" id="main" data-offset="0">
            <header>
            <Navbar myLoader={myLoader} />
            </header>
            <main className="main">{children}</main>
        </div>
        <Footer />
        </React.StrictMode>
    )
}

export default Layout
