import React from "react";
import Head from "next/head";
import dynamic from 'next/dynamic'

const Footer = dynamic(() => import( "./Footer")) ;
const Navbar= dynamic(() => import( "./Navbar")) ;
const ScrollToTop = dynamic(() => import("./ScrollToTop") )




const myLoader = ({ src, width, quality }) => {
    return `https://drcutthebarbershow.web.app/${src}?w=${width}&q=${
      quality || 75
    }`;
  };
  

const Layout = ({children}) => (
  
    
        <React.StrictMode>
        <Head>
        <title>Dr.Cut The Barber Show</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container-fluid p-0 ">
            <header>
            <Navbar myLoader={myLoader} />
            </header>
            <main>{children}</main>
            <ScrollToTop /> 
        </div>
        <footer>

        <Footer />
        </footer>
        </React.StrictMode>
    
)

export default Layout
